# Generated by Django 2.2.2 on 2019-06-19 11:28

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedCorpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Corpus')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Document')),
                ('processed_corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preprocessing.ProcessedCorpus')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, 'subword'), (1, 'word'), (2, 'n-gram/phrase'), (3, 'sentence'), (4, 'paragraph'), (5, 'text')])),
                ('embedding', picklefield.fields.PickledObjectField(blank=True, editable=False, null=True)),
                ('processed_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preprocessing.ProcessedDocument')),
            ],
        ),
    ]
