# Generated by Django 2.2.2 on 2019-06-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20190620_1245'),
        ('preprocessing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisunit',
            options={'verbose_name': 'Базовая единица анализа', 'verbose_name_plural': 'Базовые единицы анализа'},
        ),
        migrations.AlterModelOptions(
            name='processedcorpus',
            options={'verbose_name': 'Обработанный корпус', 'verbose_name_plural': 'Обработанные корпусы'},
        ),
        migrations.AlterModelOptions(
            name='processeddocument',
            options={'verbose_name': 'Обработанный документ', 'verbose_name_plural': 'Обработанные документы'},
        ),
        migrations.AddField(
            model_name='analysisunit',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisunit',
            name='value',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='analysisunit',
            unique_together={('processed_document', 'index', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='processedcorpus',
            unique_together={('corpus', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='processeddocument',
            unique_together={('processed_corpus', 'original_document')},
        ),
    ]
