# Generated by Django 2.2.2 on 2019-06-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisunit',
            options={'verbose_name': 'Базовая единица анализа', 'verbose_name_plural': 'Базовые единицы анализа'},
        ),
        migrations.AlterModelOptions(
            name='processedcorpus',
            options={'verbose_name': 'Обработанный корпус', 'verbose_name_plural': 'Обработанные корпусы'},
        ),
        migrations.AlterModelOptions(
            name='processeddocument',
            options={'verbose_name': 'Обработанный документ', 'verbose_name_plural': 'Обработанные документы'},
        ),
        migrations.AddField(
            model_name='analysisunit',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisunit',
            name='value',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
