# Generated by Django 2.2.2 on 2019-06-21 11:25

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0004_auto_20190620_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisunit',
            name='embedding',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, null=True, verbose_name='Embedding/векторизация'),
        ),
        migrations.AlterField(
            model_name='analysisunit',
            name='index',
            field=models.IntegerField(default=0, verbose_name='Индекс/позиция'),
        ),
        migrations.AlterField(
            model_name='analysisunit',
            name='processed_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preprocessing.ProcessedDocument', verbose_name='Обработанный документ'),
        ),
        migrations.AlterField(
            model_name='analysisunit',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'subword'), (1, 'word'), (2, 'n-gram/phrase'), (3, 'sentence'), (4, 'paragraph'), (5, 'text')], verbose_name='Тип единицы анализа'),
        ),
        migrations.AlterField(
            model_name='analysisunit',
            name='value',
            field=models.TextField(verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='processedcorpus',
            name='corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Corpus', verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='processedcorpus',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='processedcorpus',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='processeddocument',
            name='original_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Document', verbose_name='Оригинальный документ'),
        ),
        migrations.AlterField(
            model_name='processeddocument',
            name='processed_corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preprocessing.ProcessedCorpus', verbose_name='Обработанный корпус'),
        ),
    ]
