# Generated by Django 2.2.10 on 2020-04-09 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='area_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='district_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='locality',
            old_name='locality_name',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='locality',
            unique_together={('name', 'district')},
        ),
    ]
