# Generated by Django 2.2.10 on 2020-04-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20200409_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Долгота'),
        ),
    ]
