# Generated by Django 2.2.2 on 2019-06-27 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата парсинга')),
                ('unique_hash', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Уникальность document, datetime, text')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпусы',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Corpus', verbose_name='Корпус')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('url', models.CharField(blank=True, max_length=150, null=True, verbose_name='URL')),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Corpus', verbose_name='Корпус')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1500, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('html', models.TextField(blank=True, null=True, verbose_name='HTML')),
                ('links', models.TextField(blank=True, null=True, verbose_name='Перечень ссылок')),
                ('url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='URL')),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата парсинга')),
                ('num_views', models.IntegerField(blank=True, null=True, verbose_name='Количество просмотров')),
                ('num_shares', models.IntegerField(blank=True, null=True, verbose_name='Количество репостов/шейров')),
                ('num_comments', models.IntegerField(blank=True, null=True, verbose_name='Количество комментариев')),
                ('num_likes', models.IntegerField(blank=True, null=True, verbose_name='Количество лайков')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Author', verbose_name='Автор')),
                ('categories', models.ManyToManyField(blank=True, to='mainapp.Category', verbose_name='Категории')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Source', verbose_name='Источник')),
                ('tags', models.ManyToManyField(blank=True, to='mainapp.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
