# Generated by Django 2.2.2 on 2019-06-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicmodelling', '0001_initial'),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='topics',
            field=models.ManyToManyField(through='topicmodelling.DocumentTopic', to='topicmodelling.Topic'),
        ),
    ]
