# Generated by Django 2.2.2 on 2019-06-20 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190620_1317'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('corpus', 'name')},
        ),
    ]
