# Generated by Django 2.2.4 on 2019-10-30 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0006_auto_20190911_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_modelling_name', models.CharField(max_length=100, verbose_name='Название ТМ')),
                ('topic_id', models.CharField(max_length=50, verbose_name='ID топика')),
            ],
            options={
                'verbose_name': 'ID Топика',
                'verbose_name_plural': 'ID топиков',
                'unique_together': {('topic_modelling_name', 'topic_id')},
            },
        ),
        migrations.CreateModel(
            name='TopicGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название группы')),
                ('topic_modelling_name', models.CharField(max_length=100, verbose_name='Название ТМ')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичная группа')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('topics', models.ManyToManyField(to='mainapp.TopicID')),
            ],
            options={
                'verbose_name': 'Группа топиков',
                'verbose_name_plural': 'Группы топиков',
                'unique_together': {('name', 'owner')},
            },
        ),
    ]
