# Generated by Django 2.2.2 on 2019-06-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20190620_1322'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['corpus'], name='mainapp_cat_corpus__e53ff8_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['document'], name='mainapp_com_documen_adc970_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['corpus'], name='mainapp_tag_corpus__919fb7_idx'),
        ),
    ]
