# Generated by Django 2.2.2 on 2019-06-20 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20190620_1323'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('corpus', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('corpus', 'name')},
        ),
    ]
