# Generated by Django 2.2.2 on 2019-06-21 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20190620_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='links',
            field=models.TextField(blank=True, null=True, verbose_name='Перечень ссылок'),
        ),
        migrations.AlterField(
            model_name='author',
            name='corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Corpus', verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Corpus', verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата парсинга'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Document', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Comment', verbose_name='Ответ на...'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='document',
            name='categories',
            field=models.ManyToManyField(blank=True, to='mainapp.Category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='document',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='document',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата парсинга'),
        ),
        migrations.AlterField(
            model_name='document',
            name='html',
            field=models.TextField(blank=True, null=True, verbose_name='HTML'),
        ),
        migrations.AlterField(
            model_name='document',
            name='num_comments',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество комментариев'),
        ),
        migrations.AlterField(
            model_name='document',
            name='num_likes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество лайков'),
        ),
        migrations.AlterField(
            model_name='document',
            name='num_shares',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество репостов/шейров'),
        ),
        migrations.AlterField(
            model_name='document',
            name='num_views',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='document',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Source', verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, to='mainapp.Tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='document',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=2500, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='document',
            name='topics',
            field=models.ManyToManyField(blank=True, through='topicmodelling.DocumentTopic', to='topicmodelling.Topic', verbose_name='Топики'),
        ),
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='source',
            name='corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Corpus', verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Corpus', verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
