# Generated by Django 2.2.4 on 2019-11-29 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_viewer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewer',
            options={'verbose_name': 'Пользователь (Viewer)', 'verbose_name_plural': 'Пользователь (Viewer)'},
        ),
        migrations.AlterField(
            model_name='contentloader',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contentloader', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='viewer', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
