# Generated by Django 2.2.2 on 2019-06-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20190625_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=50000, verbose_name='Текст'),
        ),
    ]
