# Generated by Django 2.2.4 on 2019-12-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_document_sentiment_loader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='sentiment_loader',
            field=models.FloatField(blank=True, null=True, verbose_name='Тональность'),
        ),
    ]
