# Generated by Django 2.2.4 on 2019-12-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20191204_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicgroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название группы'),
        ),
    ]
