# Generated by Django 2.2.8 on 2019-12-10 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation', '0006_remove_topicideval_topic_modelling_name'),
        ('mainapp', '0016_auto_20191205_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentloader',
            name='corpus',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='corpus',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='criterions',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='topic_modelling_names',
        ),
        migrations.RemoveField(
            model_name='viewer',
            name='corpus',
        ),
        migrations.RemoveField(
            model_name='viewer',
            name='criterions',
        ),
        migrations.RemoveField(
            model_name='viewer',
            name='topic_modelling_names',
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('topic_modelling_names', models.TextField(blank=True, null=True, verbose_name='Названия тематических моделирований (через запятую без пробелов)')),
                ('corpuses', models.ManyToManyField(blank=True, to='mainapp.Corpus', verbose_name='Корпусы')),
                ('criterions', models.ManyToManyField(blank=True, to='evaluation.EvalCriterion')),
            ],
            options={
                'verbose_name': 'Группа пользователей',
                'verbose_name_plural': 'Группы пользователей',
            },
        ),
        migrations.AddField(
            model_name='contentloader',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserGroup'),
        ),
        migrations.AddField(
            model_name='expert',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserGroup'),
        ),
        migrations.AddField(
            model_name='viewer',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserGroup'),
        ),
    ]
