# Generated by Django 2.2.8 on 2020-01-22 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20191210_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='author_txt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Author', verbose_name='Автор (FK)'),
        ),
    ]
