# Generated by Django 2.2.8 on 2020-01-22 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20200122_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='is_for_content_loaders',
            field=models.BooleanField(default=False, verbose_name="Для 'Блогеров'"),
        ),
        migrations.AlterField(
            model_name='document',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Source', verbose_name='Источник*'),
        ),
        migrations.AlterField(
            model_name='document',
            name='text',
            field=models.TextField(verbose_name='Текст*'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=2500, verbose_name='Заголовок*'),
        ),
    ]
