# Generated by Django 2.2.8 on 2020-02-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_auto_20200122_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='sentiment_loader',
            field=models.FloatField(blank=True, null=True, verbose_name='Тональность*'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Заголовок*'),
        ),
    ]
