# Generated by Django 2.2.8 on 2020-02-04 13:06
import pytz
from django.db import migrations, models

from mainapp.services import batch_qs


def copy_date(apps, schema_editor):
    MyModel = apps.get_model('mainapp', 'Document')
    qs = MyModel.objects.exclude(datetime=None).order_by('id').only('datetime', 'date',)
    number_of_documents = qs.count()
    batch_size = 10000
    for i, batch in enumerate(batch_qs(qs, batch_size=batch_size)):
        print(f"Processing {i * batch_size}/{number_of_documents}")
        for j, doc in enumerate(batch):
            if i == 0:
                print(f"{j}/{batch_size}")
            doc.date = doc.datetime.date()
        MyModel.objects.bulk_update(batch, fields=['date'])


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_auto_20200204_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата публикации (dateonly)'),
        ),
        migrations.RunPython(copy_date),
    ]
