# Generated by Django 2.2.8 on 2020-02-04 13:42

from django.db import migrations


def recalc_hash(apps, schema_editor):
    MyModel = apps.get_model('mainapp', 'Document')
    qs = MyModel.objects.all().order_by('source', 'date', 'title').only('id', 'source', 'date', 'title')
    number_of_documents = qs.count()
    batch_size = 10000
    last_seen = None
    deleted = 0
    for j, doc in enumerate(qs):
        if j % batch_size == 0:
            print("!!!!!", f"Processed: {j}/{number_of_documents}")
        if (doc.source, doc.date, doc.title) == last_seen:
            doc.delete()
            deleted += 1
            if deleted % 100 == 0:
                print("!!!", "Deleted: ", deleted)
        last_seen = (doc.source, doc.date, doc.title)


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_document_date'),
    ]

    operations = [
        migrations.RunPython(recalc_hash),
    ]
