# Generated by Django 2.2.8 on 2020-02-05 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_auto_20200205_0454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='unique_hash',
        ),
    ]
