# Generated by Django 2.2.10 on 2020-05-05 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_usergroup_dashboard_presets'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('source', 'title')},
        ),
    ]
