# Generated by Django 2.2.10 on 2020-05-15 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_auto_20200505_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='date',
        ),
    ]
