# Generated by Django 2.2.10 on 2020-05-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_remove_document_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True, verbose_name='URL'),
        ),
    ]
