# Generated by Django 2.2.10 on 2020-05-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_auto_20200519_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='datetime_activity_parsed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего парсинга активности'),
        ),
    ]
