# Generated by Django 2.2.10 on 2020-05-19 12:44

from django.db import migrations

from mainapp.services import batch_qs


def init_document_datetime_activity_parsed(apps, schema_editor):
    MyModel = apps.get_model('mainapp', 'Document')
    qs = MyModel.objects.exclude(datetime=None).order_by('id').only('datetime_activity_parsed', 'datetime_created',)
    qs = qs.exclude(num_views=None)
    qs = qs.order_by('id')
    number_of_documents = qs.count()
    batch_size = 10000
    for i, batch in enumerate(batch_qs(qs, batch_size=batch_size)):
        print(f"Processing {i * batch_size}/{number_of_documents}")
        for j, doc in enumerate(batch):
            if i == 0:
                print(f"{j}/{batch_size}")
            doc.datetime_activity_parsed = doc.datetime_created
        MyModel.objects.bulk_update(batch, fields=['datetime_activity_parsed'])


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_document_datetime_activity_parsed'),
    ]

    operations = [
        migrations.RunPython(init_document_datetime_activity_parsed),
    ]
