# Generated by Django 2.2.10 on 2020-05-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_auto_20200523_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='datetime_activity_es_updated',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата последнего апдейта активности в ES'),
        ),
    ]
