# Generated by Django 2.2.13 on 2020-07-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_document_class_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='class_label',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Класс (разметка)'),
        ),
    ]
