# Generated by Django 2.2.13 on 2020-09-26 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_auto_20200926_1848'),
        ('mainapp', '0036_auto_20200711_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Оригинал был удалён/недоступен'),
        ),
        migrations.AddField(
            model_name='document',
            name='social_network_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scraping.SocialNetworkAccount', verbose_name='Аккаунт (соц сетей)'),
        ),
    ]
