# Generated by Django 2.2.13 on 2020-10-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_auto_20200926_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Идентификатор комментария'),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('document', 'comment_id')},
        ),
    ]
