# Generated by Django 2.2.13 on 2020-11-16 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluation', '0009_auto_20200226_1245'),
        ('mainapp', '0038_auto_20201006_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_modelling_name', models.TextField(verbose_name='Название тематической модели')),
                ('subscription_type', models.PositiveSmallIntegerField(choices=[(-1, 'Негатив'), (0, 'Последние новости'), (1, 'Позитив')], verbose_name='Тип подписки')),
                ('threshold', models.FloatField(blank=True, null=True, verbose_name='Порог критерия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_fast', models.BooleanField(default=False, verbose_name='Оперативный')),
                ('criterion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluation.EvalCriterion', verbose_name='Критерий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'unique_together': {('user', 'criterion', 'topic_modelling_name', 'subscription_type')},
            },
        ),
    ]
