# Generated by Django 2.2.13 on 2020-11-16 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_auto_20201116_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionReportObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=1000, null=True, unique=True, verbose_name='URL')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Source', verbose_name='Источник')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Subscription', verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'Объект отчёта по подписке',
                'verbose_name_plural': 'Объекты отчётов по подпискам',
                'unique_together': {('subscription', 'url', 'source')},
            },
        ),
    ]
