# Generated by Django 2.2.13 on 2020-11-16 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0041_subscriptionreportobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionreportobject',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания объекта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionreportobject',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='Отправлен'),
        ),
    ]
