# Generated by Django 2.2.13 on 2020-11-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0042_auto_20201116_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionreportobject',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True, verbose_name='URL'),
        ),
    ]
