# Generated by Django 2.2.13 on 2020-11-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0044_subscriptionreportobject_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='tm_num_threshold',
            field=models.FloatField(default=2, verbose_name='Порог принадлежности к ТМ (количество топиков)'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='tm_weight_threshold',
            field=models.FloatField(default=0.05, verbose_name='Порог принадлежности к ТМ (вес)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='threshold',
            field=models.FloatField(default=0.1, verbose_name='Порог критерия'),
        ),
    ]
