# Generated by Django 2.2.13 on 2020-11-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0045_auto_20201120_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='threshold',
            field=models.IntegerField(default=10, verbose_name='Порог критерия (персентиль)'),
        ),
    ]
