# Generated by Django 2.2.13 on 2020-12-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0046_auto_20201124_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionreportobject',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tm_weight_threshold',
            field=models.FloatField(default=0.05, verbose_name='Порог принадлежности к ТМ (персентиль)'),
        ),
    ]
