# Generated by Django 2.2.13 on 2020-12-15 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0047_auto_20201207_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='parent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.TopicGroup', verbose_name='Группа топиков'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='parent_group_threshold',
            field=models.FloatField(default=0.05, verbose_name='Порог принадлежности к группе'),
        ),
    ]
