# Generated by Django 2.2.13 on 2021-01-12 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0048_auto_20201215_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='corpus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Corpus', verbose_name='Корпус'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='keyword_query',
            field=models.TextField(blank=True, null=True, verbose_name='Запрос по ключевому слову'),
        ),
        migrations.AlterField(
            model_name='subscriptionreportobject',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True, verbose_name='Заголовок'),
        ),
    ]
