SEARCH_CUTOFF_CONFIG = {
    "SEARCH_LVL_LIGHT": {
        "RIGID_CUTOFF": 10,
        "IMMEDIATE_DIFFERENTIAL_CUTOFF": 5,
        "GLOBAL_DIFFERENTIAL_CUTOFF": 10,
        "ABS_MAX_RESULTS_CUTOFF": 50000,
        "REL_MAX_RESULTS_CUTOFF": 0.9
    },
    "SEARCH_LVL_HARD": {
        "RIGID_CUTOFF": 8,
        "IMMEDIATE_DIFFERENTIAL_CUTOFF": 4,
        "GLOBAL_DIFFERENTIAL_CUTOFF": 8,
        "ABS_MAX_RESULTS_CUTOFF": 30000,
        "REL_MAX_RESULTS_CUTOFF": 0.75
    }
}
