# Generated by Django 2.2.2 on 2019-06-20 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_document_topics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='corpus',
            options={'verbose_name': 'Корпус', 'verbose_name_plural': 'Корпусы'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name': 'Источник', 'verbose_name_plural': 'Источники'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.RemoveField(
            model_name='author',
            name='source',
        ),
        migrations.AddField(
            model_name='author',
            name='corpus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Corpus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='corpus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Corpus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Source'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='corpus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Corpus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='document',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Document'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corpus',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
