# Generated by Django 2.2.2 on 2019-06-20 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20190620_1322'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('source', 'title', 'datetime')},
        ),
    ]
