# Generated by Django 2.2.8 on 2020-03-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200226_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardpreset',
            name='corpus',
        ),
        migrations.RemoveField(
            model_name='dashboardpreset',
            name='topic_modelling_name',
        ),
        migrations.AddField(
            model_name='widget',
            name='topic_modelling_name',
            field=models.CharField(default='bigartm_two_years', max_length=100, verbose_name='Название ТМ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='widget',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Overall positive-negative'), (1, 'Dynamic'), (2, 'Top news'), (5, 'Bottom news'), (3, 'Top topics'), (4, 'Source distribution')], default=0),
        ),
    ]
