# Generated by Django 2.2.8 on 2020-03-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200327_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='datetime_from',
            field=models.DateField(blank=True, null=True, verbose_name='Отфильтровать с'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='datetime_to',
            field=models.DateField(blank=True, null=True, verbose_name='Отфильтровать до'),
        ),
    ]
