# Generated by Django 2.2.8 on 2020-03-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200327_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='name_query',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Предмет запроса'),
        ),
        migrations.AddField(
            model_name='widget',
            name='ner_query',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Список сущностей'),
        ),
    ]
