# Generated by Django 2.2.8 on 2020-04-01 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200401_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='monitoring_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.MonitoringObject', verbose_name='Объект мониторинга'),
        ),
    ]
