# Generated by Django 2.2.10 on 2020-04-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200401_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='params',
            field=models.TextField(blank=True, null=True),
        ),
    ]
