# Generated by Django 2.2.10 on 2020-05-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20200415_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Overall positive-negative'), (1, 'Dynamic'), (2, 'Top news'), (5, 'Bottom news'), (6, 'Last news'), (3, 'Top topics'), (4, 'Source distribution'), (7, 'Map distribution')], default=0),
        ),
    ]
