# Generated by Django 2.2.10 on 2020-05-15 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20200424_1733'),
        ('dashboard', '0011_auto_20200505_1743'),
    ]

    operations = [
    ]
