# Generated by Django 2.2.13 on 2020-08-29 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20200828_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='monitoring_objects_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.MonitoringObjectsGroup', verbose_name='Группа объектов мониторинга'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Overall positive-negative'), (1, 'Dynamic'), (2, 'Top news'), (5, 'Bottom news'), (6, 'Last news'), (3, 'Top topics'), (4, 'Source distribution'), (7, 'Map distribution'), (8, 'Map coverage'), (9, 'Monitoring objects compare')], default=0),
        ),
    ]
