# Generated by Django 2.2.13 on 2020-08-29 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20200829_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='criterion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluation.EvalCriterion'),
        ),
    ]
