# Generated by Django 2.2.13 on 2020-09-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_auto_20200926_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramLoginPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=1000, verbose_name='Логин аккаунта')),
                ('password', models.CharField(max_length=1000, verbose_name='Пароль аккаунта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменнеия')),
            ],
        ),
        migrations.AddField(
            model_name='socialnetworkaccount',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Конфеденциальность аккаунта'),
        ),
        migrations.AddField(
            model_name='socialnetworkaccount',
            name='is_valid',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Неверифицированный'), (1, 'Верифицированный'), (2, 'Непроверенный')], default=2, max_length=1000, verbose_name='Состояние аккаунта'),
        ),
        migrations.AddField(
            model_name='socialnetworkaccount',
            name='nickname',
            field=models.CharField(default='', max_length=1000, verbose_name='Никнэйм аккаунта'),
            preserve_default=False,
        ),
    ]
