# Generated by Django 2.2.13 on 2020-09-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_auto_20200928_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetworkaccount',
            name='num_followers',
            field=models.BigIntegerField(default=0, verbose_name='Количество подписчиков'),
        ),
        migrations.AddField(
            model_name='socialnetworkaccount',
            name='num_follows',
            field=models.BigIntegerField(default=0, verbose_name='Количество подписок'),
        ),
        migrations.AlterField(
            model_name='socialnetworkaccount',
            name='is_valid',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Неверифицированный'), (1, 'Верифицированный'), (2, 'Непроверенный')], default=2, verbose_name='Состояние аккаунта'),
        ),
    ]
