# Generated by Django 2.2.13 on 2020-09-29 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0006_auto_20200929_0113'),
        ('scraping', '0006_auto_20200929_1226'),
    ]

    operations = [
    ]
