# Generated by Django 2.2.13 on 2020-10-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0010_auto_20200929_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetworkaccount',
            name='is_valid',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Непроверенный'), (1, 'Верифицированный'), (2, 'Неверифицированный')], default=0, verbose_name='Состояние аккаунта'),
        ),
    ]
