# Generated by Django 2.2.13 on 2020-10-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0011_auto_20201001_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetworkaccount',
            name='is_valid',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Непроверенный'), (1, 'Верифицированный'), (2, 'Неверифицированный')], default=1, verbose_name='Состояние аккаунта'),
        ),
    ]
