# Generated by Django 2.2.13 on 2020-10-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0014_vkloginpass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkloginpass',
            name='datetime_news_feed_limit_reached',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата когда достигнут лимит по News Feed'),
        ),
        migrations.AlterField(
            model_name='vkloginpass',
            name='datetime_wall_get_limit_reached',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата когда достигнут лимит по Wall Get'),
        ),
    ]
