# Generated by Django 2.2.13 on 2020-10-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0015_auto_20201006_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('social_network', models.PositiveSmallIntegerField(choices=[(0, 'Facebook'), (1, 'VK'), (2, 'Twitter'), (3, 'Instagram'), (4, 'Telegram'), (5, 'Youtube')], verbose_name='Соц. сеть')),
                ('query', models.CharField(max_length=1000, verbose_name='Запрос')),
                ('priority_rate', models.FloatField(default=50, verbose_name='Приоритет парсинга (от 0 до 100')),
                ('is_active', models.BooleanField(default=True, verbose_name='Парсинг активирован')),
                ('datetime_last_parsed', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего успешного парсинга')),
            ],
            options={
                'verbose_name': 'Запрос для мониторинга',
                'verbose_name_plural': 'Запрос для мониторинга',
                'unique_together': {('query', 'social_network')},
            },
        ),
    ]
