# Generated by Django 2.2.13 on 2020-10-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0016_monitoringquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkloginpass',
            name='datetime_news_feed_updated',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата, когда обновлено количество запросов по News Feed'),
        ),
        migrations.AddField(
            model_name='vkloginpass',
            name='datetime_wall_get_updated',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата, когда обновлено количество запросов по Wall Get'),
        ),
        migrations.AlterField(
            model_name='vkloginpass',
            name='datetime_news_feed_limit_reached',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата, когда достигнут лимит по News Feed'),
        ),
        migrations.AlterField(
            model_name='vkloginpass',
            name='datetime_wall_get_limit_reached',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата, когда достигнут лимит по Wall Get'),
        ),
    ]
