# Generated by Django 2.2.13 on 2020-10-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0017_auto_20201009_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeAuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=100, verbose_name='APP ID приложения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменнеия')),
            ],
            options={
                'verbose_name': 'YouTube - доступ',
                'verbose_name_plural': 'YouTube - доступ',
            },
        ),
    ]
