# Generated by Django 2.2.13 on 2020-10-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0018_youtubeauthtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubeauthtoken',
            name='app_id',
        ),
        migrations.AddField(
            model_name='youtubeauthtoken',
            name='token_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='TOKEN ID'),
        ),
    ]
