# Generated by Django 2.2.13 on 2020-10-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0019_auto_20201013_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeauthtoken',
            name='datetime_videos_limit_reached',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата, когда достигнут лимит по get video'),
        ),
        migrations.AddField(
            model_name='youtubeauthtoken',
            name='datetime_videos_updated',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата, когда обновлено количество запросов по get video'),
        ),
        migrations.AddField(
            model_name='youtubeauthtoken',
            name='videos_limit_used',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Get video запросов использовано'),
        ),
    ]
