# Generated by Django 2.2.13 on 2020-10-13 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0020_auto_20201013_1600'),
        ('scraping', '0018_monitoringquery_max_requests_per_session'),
    ]

    operations = [
    ]
