# Generated by Django 2.2.13 on 2020-10-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0021_merge_20201014_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetworkaccount',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=1500, null=True, verbose_name='Описание канала'),
        ),
        migrations.AddField(
            model_name='socialnetworkaccount',
            name='keywords',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Ключевые слова канала'),
        ),
        migrations.AddField(
            model_name='socialnetworkaccount',
            name='posts_count',
            field=models.BigIntegerField(blank=True, default=None, null=True, verbose_name='Количество постов/видео'),
        ),
        migrations.AddField(
            model_name='socialnetworkaccount',
            name='topic_ids',
            field=models.CharField(blank=True, default=None, max_length=1500, null=True, verbose_name='Темы, относящиеся к каналу, разделенные знаком "|"'),
        ),
        migrations.AddField(
            model_name='socialnetworkaccount',
            name='view_count',
            field=models.BigIntegerField(blank=True, default=None, null=True, verbose_name='Количество просмотров профиля/канала'),
        ),
    ]
