metricbeat.modules:
  - module: system
    metricsets: ["cpu","memory","network","diskio"]
    enabled: true
    period: 15s
    processes: ['.*']

  - module: docker
    metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s

  - module: kibana
    metricsets: ["status"]
    period: 10s
    hosts: ["kibana_cluster:5601"]
    basepath: ""
    enabled: true

output.elasticsearch:
  hosts: ["elasticsearch1:9200", "elasticsearch2:9200", "elasticsearch3:9200"]

# setup.kibana:
#   host: "http://kibana_cluster:5601"

# setup.dashboards.enabled: true

metricbeat.max_start_delay: 10s
