# Generated by Django 2.2.10 on 2020-02-26 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_remove_document_topics'),
        ('topicmodelling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='topic_corpus',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_parent',
        ),
        migrations.AlterUniqueTogether(
            name='topiccorpus',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='topiccorpus',
            name='corpus',
        ),
        migrations.RemoveField(
            model_name='topicunit',
            name='topic',
        ),
        migrations.DeleteModel(
            name='DocumentTopic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='TopicCorpus',
        ),
        migrations.DeleteModel(
            name='TopicUnit',
        ),
    ]
