# Generated by Django 2.2.2 on 2019-06-20 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topicmodelling', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttopic',
            options={'verbose_name': 'Связь документа и топика', 'verbose_name_plural': 'Связи документов и топиков'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Топик', 'verbose_name_plural': 'Топики'},
        ),
        migrations.AlterModelOptions(
            name='topiccorpus',
            options={'verbose_name': 'Корпус топиков', 'verbose_name_plural': 'Корпусы топиков'},
        ),
        migrations.AlterModelOptions(
            name='topicunit',
            options={'verbose_name': 'Единица-описание топика', 'verbose_name_plural': 'Единицы-описания топика'},
        ),
    ]
