# Generated by Django 2.2.2 on 2019-06-20 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20190620_1245'),
        ('topicmodelling', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttopic',
            options={'verbose_name': 'Связь документа и топика', 'verbose_name_plural': 'Связи документов и топиков'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Топик', 'verbose_name_plural': 'Топики'},
        ),
        migrations.AlterModelOptions(
            name='topiccorpus',
            options={'verbose_name': 'Корпус топиков', 'verbose_name_plural': 'Корпусы топиков'},
        ),
        migrations.AlterModelOptions(
            name='topicunit',
            options={'verbose_name': 'Единица-описание топика', 'verbose_name_plural': 'Единицы-описания топика'},
        ),
        migrations.AlterUniqueTogether(
            name='documenttopic',
            unique_together={('topic', 'document')},
        ),
        migrations.AlterUniqueTogether(
            name='topiccorpus',
            unique_together={('corpus', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='topicunit',
            unique_together={('topic', 'text')},
        ),
    ]
