# Generated by Django 2.2.2 on 2019-06-21 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topicmodelling', '0005_auto_20190620_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttopic',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Document', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='documenttopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topicmodelling.Topic', verbose_name='Топик'),
        ),
        migrations.AlterField(
            model_name='documenttopic',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topicmodelling.TopicCorpus', verbose_name='Корпус топиков'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topicmodelling.Topic', verbose_name='Родительский топик'),
        ),
        migrations.AlterField(
            model_name='topiccorpus',
            name='corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Corpus', verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='topiccorpus',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='topiccorpus',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='topicunit',
            name='text',
            field=models.CharField(max_length=100, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='topicunit',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topicmodelling.Topic', verbose_name='Топик'),
        ),
        migrations.AlterField(
            model_name='topicunit',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес'),
        ),
    ]
