version: '3'

services:
  airflow-postgresql:
    image: 'bitnami/postgresql:11.4.0'
    environment:
      - POSTGRESQL_DATABASE=${AIRFLOW_DB_NAME}
      - POSTGRESQL_USERNAME=${AIRFLOW_DB_USER}
      - POSTGRESQL_PASSWORD=${AIRFLOW_DB_PASSWORD}
    volumes:
      - airflow:/bitnami/postgresql
    networks:
      - network
    restart: always
  airflow-redis:
    image: 'bitnami/redis:5.0.5'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - airflow:/bitnami
    networks:
      - network
    restart: always
  airflow-worker:
    image: "bitnami/airflow-worker:1.10.3"
    environment:
      - AIRFLOW_WEBSERVER_PORT_NUMBER=8001
      - AIRFLOW_FERNET_KEY=${AIRFLOW_FERNET_KEY}
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=${AIRFLOW_DB_NAME}
      - AIRFLOW_DATABASE_USERNAME=${AIRFLOW_DB_USER}
      - AIRFLOW_DATABASE_PASSWORD=${AIRFLOW_DB_PASSWORD}
      - AIRFLOW_DATABASE_HOST=airflow-postgresql
      - REDIS_HOST=airflow-redis
    volumes:
      - airflow:/bitnami
      - ../dags:/opt/bitnami/airflow/dags
    networks:
      - network
    depends_on:
      - airflow-redis
      - airflow-postgresql
    restart: always
  airflow-scheduler:
    image: "bitnami/airflow-scheduler:1.10.3"
    environment:
      - AIRFLOW_WEBSERVER_PORT_NUMBER=8001
      - AIRFLOW_FERNET_KEY=${AIRFLOW_FERNET_KEY}
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=${AIRFLOW_DB_NAME}
      - AIRFLOW_DATABASE_USERNAME=${AIRFLOW_DB_USER}
      - AIRFLOW_DATABASE_PASSWORD=${AIRFLOW_DB_PASSWORD}
      - AIRFLOW_LOAD_EXAMPLES=yes
      - AIRFLOW_DATABASE_HOST=airflow-postgresql
      - REDIS_HOST=airflow-redis
    volumes:
      - airflow:/bitnami
      - ../dags:/opt/bitnami/airflow/dags
    networks:
      - network
    depends_on:
      - airflow-redis
      - airflow-postgresql
    restart: always
  airflow:
    image: "bitnami/airflow:1.10.3"
    environment:
      - AIRFLOW_WEBSERVER_PORT_NUMBER=8001
      - AIRFLOW_FERNET_KEY=${AIRFLOW_FERNET_KEY}
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=${AIRFLOW_DB_NAME}
      - AIRFLOW_DATABASE_USERNAME=${AIRFLOW_DB_USER}
      - AIRFLOW_DATABASE_PASSWORD=${AIRFLOW_DB_PASSWORD}
      - AIRFLOW_PASSWORD=${AIRFLOW_PASSWORD}
      - AIRFLOW_USERNAME=${AIRFLOW_USER}
      - AIRFLOW_EMAIL=${AIRFLOW_EMAIL}
      - AIRFLOW_DATABASE_HOST=airflow-postgresql
      - REDIS_HOST=airflow-redis
      - AIRFLOW__SMTP__SMTP_HOST=${AIRFLOW_SMTP_HOST}
      - AIRFLOW__SMTP__SMTP_PORT=${AIRFLOW_SMTP_PORT}
      - AIRFLOW__SMTP__SMTP_USER=${AIRFLOW_SMTP_USER}
      - AIRFLOW__SMTP__SMTP_PASSWORD=${AIRFLOW_SMTP_PASSWORD}
    ports:
      - '8001:8001'
    volumes:
      - airflow:/bitnami
      - ../dags:/opt/bitnami/airflow/dags
    networks:
      - network
    depends_on:
      - airflow-redis
      - airflow-postgresql
    restart: always

volumes:
  airflow:
    driver: local
