version: '3'

services:
  airflow-worker:
    build:
      context: ../airflow-worker
      dockerfile: Dockerfile
    volumes:
      - airflow:/bitnami
      - ../dags:/opt/bitnami/airflow/dags
      - ./airflow_plugins:/opt/bitnami/airflow/plugins
      - ../airflow-worker/airflow_worker_plugins/sentry_plugin:/opt/bitnami/airflow/plugins/sentry_plugin
      - ../web:/django
