version: '3'

services:
  web:
    build:
      context: ../web
      dockerfile: docker/Dockerfile
    command: ["start-dev"]
    volumes:
      - ../web:/opt/app
      - media_root:/opt/app/media_root
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
  nginx:
    volumes:
      - ./nginx-app-dev.conf:/etc/nginx/conf.d/app.conf
  kibana:
    ports:
      - "5601:5601"
  elasticsearch:
    environment:
      - cluster.name="elk-nlpmonitor-cluster"
      - network.host=0.0.0.0
      - discovery.type=single-node
      - discovery.zen.minimum_master_nodes=1
      - ${ELASTIC_JAVA_OPTIONS}
