version: '3'

services:
  web:
    image: ${WEB_IMAGE}
    command: ["start-prod"]
    volumes:
      - static_root:/opt/app/static_root
      - media_root:/opt/app/media_root
      - django_root:/opt/app
  nginx:
    volumes:
      - ./nginx-app-prod.conf:/etc/nginx/conf.d/app.conf
  kibana:
    environment:
      - SERVER_REWRITEBASEPATH=true
      - SERVER_BASEPATH=${KIBANA_PRIVATE_PATH}