version: '3'

services:
  web:
    image: ${WEB_IMAGE}
    command: ["start-prod"]
    volumes:
      - static_root:/opt/app/static_root
      - media_root:/opt/app/media_root
      - django_root:/opt/app
      - /_DATA/big_data/:/big_data/
  nginx:
    volumes:
      - ./nginx-app-prod.conf:/etc/nginx/conf.d/app.conf
      - ../certbot/conf:/etc/letsencrypt:rw
      - ../certbot/www:/var/www/certbot:rw
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  db:
    ports:
      - "5456:5432"
  bert_as_service:
    build:
      context: ./bert_as_service
      dockerfile: Dockerfile
    volumes:
      - /home/a.bekbaganbetov/tempdocker/models/rubert_tf_experimental/:/model
    expose:
      - 5555
      - 5556
    networks:
      - network
    restart: always
  apertium-flask:
    build:
      context: ../containers/apertium
      dockerfile: Dockerfile
    expose:
      - 8005
    networks:
      - network
    tty: true
    stdin_open: true
