version: '3'

services:
  web:
    env_file:
      - ../.env
    expose:
      - 8000
    depends_on:
      - db
      - redis
      - elastic
  nginx:
    image: "nginx:1.17.0"
    ports:
      - "80:80"
    volumes:
      - static_root:/static_root
      - media_root:/media_root
    depends_on:
      - web
  db:
    image: "mariadb/columnstore:1.2.3"
    expose:
      - 3306
    volumes:
      - maria_data_etc:/usr/local/mariadb/columnstore/etc
      - maria_data_data1:/usr/local/mariadb/columnstore/data1
      - maria_data_local:/usr/local/mariadb/columnstore/local
      - maria_data_mysql_db:/usr/local/mariadb/columnstore/mysql/db
    environment:
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_NUM_BLOCKS_PCT=${MARIADB_NUM_BLOCKS_PCT}
      - MARIADB_TOTAL_UM_MEMORY=${MARIADB_TOTAL_UM_MEMORY}
  elastic:
    image: "elasticsearch:7.1.1"
    expose:
      - 9200
      - 9300
    environment:
      - discovery.type=single-node
  kibana:
    image: "kibana:7.1.1"
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=elastic
  redis:
    image: "redis:5.0.5"

volumes:
  maria_data_etc:
    driver: local
  maria_data_data1:
    driver: local
  maria_data_local:
    driver: local
  maria_data_mysql_db:
    driver: local
  redis:
    driver: local
  media_root:
    driver: local
  static_root:
    driver: local
