version: '3'

services:
  web:
    image: ${WEB_IMAGE}
    command: ["start-prod"]
    volumes:
      - static_root:/opt/app/static_root
      - media_root:/opt/app/media_root
      - django_root:/opt/app
  nginx:
    volumes:
      - ./nginx-app-prod.conf:/etc/nginx/conf.d/app.conf
  elasticsearch:
    environment:
      - cluster.name="elk-nlpmonitor-cluster"
      - network.host=0.0.0.0
      - discovery.type=single-node
      - discovery.zen.minimum_master_nodes=1
      - ${ELASTIC_JAVA_OPTIONS}