version: '3'

services:
  airflow-worker:
    build:
      context: ../airflow-worker
      dockerfile: Dockerfile
    volumes:
      - ../web:/django
      - ./airflow.cfg.dev:/opt/bitnami/airflow/airflow.cfg
