version: '3'

services:
  airflow-worker:
    image: ${AIRFLOW_WORKER_IMAGE}
    volumes:
      - django_root:/django
      - ./airflow.cfg.prod:/opt/bitnami/airflow/airflow.cfg
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 10240M
        reservations:
          cpus: '0.1'
          memory: 1024M
  airflow:
    volumes:
      - ./airflow.cfg.prod:/opt/bitnami/airflow/airflow.cfg
  airflow-scheduler:
    volumes:
      - ./airflow.cfg.prod:/opt/bitnami/airflow/airflow.cfg
