# Generated by Django 2.2.2 on 2019-06-27 04:14

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedCorpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Corpus', verbose_name='Корпус')),
            ],
            options={
                'verbose_name': 'Обработанный корпус',
                'verbose_name_plural': 'Обработанные корпусы',
            },
        ),
        migrations.CreateModel(
            name='ProcessedDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Document', verbose_name='Оригинальный документ')),
                ('processed_corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preprocessing.ProcessedCorpus', verbose_name='Обработанный корпус')),
            ],
            options={
                'verbose_name': 'Обработанный документ',
                'verbose_name_plural': 'Обработанные документы',
            },
        ),
        migrations.CreateModel(
            name='AnalysisUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, 'subword'), (1, 'word'), (2, 'n-gram/phrase'), (3, 'sentence'), (4, 'paragraph'), (5, 'text')], verbose_name='Тип единицы анализа')),
                ('value', models.TextField(verbose_name='Значение')),
                ('index', models.IntegerField(default=0, verbose_name='Индекс/позиция')),
                ('embedding', picklefield.fields.PickledObjectField(blank=True, editable=False, null=True, verbose_name='Embedding/векторизация')),
                ('unique_hash', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Уникальность processed_document, index, value')),
                ('processed_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preprocessing.ProcessedDocument', verbose_name='Обработанный документ')),
            ],
            options={
                'verbose_name': 'Базовая единица анализа',
                'verbose_name_plural': 'Базовые единицы анализа',
            },
        ),
        migrations.AddIndex(
            model_name='processeddocument',
            index=models.Index(fields=['processed_corpus'], name='preprocessi_process_fad705_idx'),
        ),
        migrations.AddIndex(
            model_name='processeddocument',
            index=models.Index(fields=['original_document'], name='preprocessi_origina_41bc68_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='processeddocument',
            unique_together={('processed_corpus', 'original_document')},
        ),
        migrations.AddIndex(
            model_name='processedcorpus',
            index=models.Index(fields=['corpus'], name='preprocessi_corpus__e75e7e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='processedcorpus',
            unique_together={('corpus', 'name')},
        ),
    ]
