# Generated by Django 2.2.4 on 2019-08-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedcorpus',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
    ]
