# Generated by Django 2.2.2 on 2019-06-20 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20190620_1324'),
        ('preprocessing', '0003_auto_20190620_1323'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='processedcorpus',
            unique_together={('corpus', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='processeddocument',
            unique_together={('processed_corpus', 'original_document')},
        ),
    ]
